#!/usr/bin/python
#coding: utf-8

import MySQLdb
con= MySQLdb.connect(host='192.168.3.***',user='******',passwd='******',db='dddate',charset='utf8')

cursor =con.cursor()
sql ="SELECT * from da_account_trade where biztype in (1,3) and inouttype=1 and `status`=20 group by accountid"
cursor.execute(sql)
row=cursor.fetchall()
print row

cursor.close()
con.close()
